# # # coding: utf-8
# # # import re
# # # import inverted_index
# # #
# # # msg = '我覺得我眼睛有點乾'
# # #
# # # pattern = '我覺得'
# # #
# # # txt = re.match(pattern,msg)
# # #
# # # # if txt != None:
# # # #     print(msg.split(pattern))
# # # keyword =''
# # #
# # # if msg[0:3] == '我覺得':
# # #     sentence = msg.split('我覺得')[1]
# # #     print(inverted_index.main(sentence))
# #
# #
# # import tool
# import urllib.parse
#
#
# def left():
#     left = [['貓爪蒸蛋【VICI的懶人廚房】',
#       'https://img.cook1cook.com/upload/cover/17/10/2597714042478411710_thumb.jpg',
#       "['雞蛋']",
#       "['一顆']",
#       "['11一顆蛋對應二個貓爪模2先把蛋黃及蛋白分開後，接著二個各自打散', '23用隔水加熱法，將模放入裝水的鍋中，開微火4用吸管小心的把蛋黃先滴入爪肉裡', '35待蛋黃凝固後，將一半的蛋白分別倒入二個貓瓜內', '46等蛋白表層也略凝固時，再把剩下的蛋黃分二邊全倒入貓瓜模', '57蛋黃表面凝固時，把剩下的蛋白分二邊全倒入模具裡。待表面完全凝固即可起鍋', '6蒸的過程可隨家裡鍋具自行調整火力，基本上火不要太大才不會焦掉每倒一層後，可蓋上蓋子加速蒸蛋表面凝固', '7蒸好的貓爪搭配著兒童餐盤，就是一份卡哇伊的兒童餐嘍']",
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['Egg Omelet 蛋奄列',
#       'https://img.cook1cook.com/upload/cover/92/52/2642714396796809252_thumb.JPG',
#       "['蛋']",
#       "['']",
#       "['1先把蛋攪拌成蛋漿，鹽少許繼續攪拌(備用)', '2熱鍋下材料炒至軟身,灑上適量黑胡椒,上碟備用', '3另一鍋或同鍋洗淨抹乾後,熱鍋中火牛油1片,下蛋漿', '4放已熟材料在蛋面,然後從一端輕輕挑起，將蛋餅捲起，煎至金黃色完成。']",
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['小飯煲半熟蛋',
#       'https://img.cook1cook.com/upload/cover/33/40/4718514404270023340_thumb.jpg',
#       "['蛋']",
#       "['1隻']",
#       "['1－室溫蛋用微波爐保鮮紙包好', '2－小飯煲下滾水，放進蛋蓋上蓋子煮7分鐘', '3－取出蛋撕去保鮮紙，放入冰水內，再放入雪櫃雪一小時，取出用匙羮脫殼便完成。*雪過的半熟蛋黃會creamyD㗎！']",
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['影音食譜 法式吐司鮮奶捲+雪花糕',
#       'https://img.cook1cook.com/upload/cover/68/45/2604615012493426845_thumb.PNG',
#       "['吐司']",
#       "['適量']",
#       "['1詳細影音食譜:http://goo.gl/xYddGz', '2鮮奶餡用中火,一直攪拌煮至濃稠', '3容器抹油,倒入1冷藏凝固', '4取出切適當大小,沾椰子粉就是雪花糕', '5吐司去邊,桿成薄片', '6包入鮮奶餡,輕壓固定', '7雞蛋加一大匙水打散', '8吐司捲沾裹6', '9用少許油,煎至表面金黃取出切塊即可!']",
#       {'Calorie_correction': 283.0,
#        'Moisture': 33.3,
#        'Crude_protein': 10.0,
#        'Crude_fat': 6.1,
#        'Saturated_fat': 2.9,
#        'Total_carbohydrates': 49.2,
#        'Dietary_fiber': 4.2,
#        'Total_carbohydrate': 6.7,
#        'glucose': 2.1,
#        'fructose': 2.9,
#        'Galactose': 0.0,
#        'maltose': 1.6,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 355.0,
#        'Potassium': 137.0,
#        'calcium': 18.0,
#        'magnesium': 46.0,
#        'iron': 1.3,
#        'Zinc': 1.4,
#        'phosphorus': 130.0,
#        'copper': 0.0,
#        'manganese': 0.0,
#        'VitaminB1': 0.22,
#        'VitaminB2': 0.07,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.21,
#        'VitaminC': 0.0,
#        'Folic_acid': 66.7,
#        'VitaminA': 5.0,
#        'VitaminD': 0.0,
#        'VitaminE': 2.04}],
#      ['雲朵蛋Cloud Egg',
#       'https://img.cook1cook.com/upload/cover/4/53/1200541516674027453_thumb.jpg',
#       "['雞蛋']",
#       "['1']",
#       "['1以200度預熱焗爐10分鐘分開蛋白同蛋黃，蛋黃要保持完整用電動打蛋器打發蛋白至企身', '2在焗盤上放上蛋白，形成一團雲蛋白中間預留一個窿，放入蛋黃', '3以200度焗20-25分鐘就完成**BB吃的是全熟蛋黃，所以焗的時間較長。如果大人食，不要全熟蛋，焗的時間可以短一點。']",
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['櫻花茶碗蒸(昆布鰹魚清湯)',
#       'https://img.cook1cook.com/upload/cover/201803/1/767165abb98a1e4f1a6_thumb.jpg',
#       "['雞蛋']",
#       "['4隻']",
#       "['1材料：(2人份量)雞蛋4隻、昆布鰹魚清湯適量(可用清雞湯代替)、味醂1茶匙、海鹽1茶匙、櫻花蝦少許、鹽漬櫻花2-4朵', '2鹽漬櫻花用清水浸30分鐘，除去鹽份，用廚房紙印乾水份，備用。', '3櫻花蝦用清水浸30分鐘，用廚房紙印乾水份，備用。', '4雞蛋打匀後加昆布鰹魚清湯混合(比例1：1.5，即1份雞蛋：1.5份昆布鰹魚清湯)，加入海鹽及味醂拌匀，用小篩隔過濾泡沫，倒入已加熱容器内，放上櫻花蝦，蓋上微波爐保鮮紙，隔水大火蒸5分鐘，熄火，不要打開蓋焗20分鐘，加上樱花裝飾，即成。', '5昆布鰹魚清湯：水500cc、昆布10g、魚片15g', '6昆布用廚房紙巾輕輕把灰塵抹掉(昆布上面白色是鮮味來源，不可用水洗掉)，加水浸至少4個小時。', '7將昆布水小火加熱至60度煮約3分鐘，取出昆布；加入鰹魚片小火煮約2-3分鐘，熄火静置20分鐘；用廚房紙及小篩隔過濾清湯，可得昆布鰹魚清湯約300cc。(完成昆布鰹魚清湯可放在密封瓶內放進雪櫃可保存一個月以上)']",
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['果醬該怎麼吃呢  附『實作影片』',
#       'https://img.cook1cook.com/upload/cover/201804/91/105672-1524661964_thumb.JPG',
#       "['吐司']",
#       "['適量']",
#       "['1果醬的6大類料理運用：', '21.)做麵包🍞：將材料中的糖份量，改以果醬取代，就能做出帶有水果風味的各式手作麵包！', '32.)抹醬：吐司、麵包、煎餅、鬆餅、饅頭、', '4可麗餅、法式吐司、雞蛋泡泡芙Popovers...等。', '53.)沾醬、醬汁:沙拉醬、涼拌菜醬料', '6a.)百香果油醋醬：冷壓橄欖油2大匙、百香果鳳梨果醬2大匙、梅醋1.5大匙、塩1/4茶匙、粗黑胡椒粒1/8茶匙（全部食材混勻至乳化為止！）', '7b.)涼拌菜醬料：百香果鳳梨果醬100-80g，糯米醋3茶匙，乾燥洋香菜葉1/8茶匙（可用在青木瓜、南瓜、大頭菜、小黃瓜、青花菜梗等！）', '8甜點🍰:製作蛋糕、餅乾、司康scone沾醬、冰淇淋淋醬、', '9冰淇淋、起司蛋糕淋醬、奶酪淋醬', '105.)水果優格：🍇【最聰明的吃法】✔️健康新概念➜可以自己製作優格，網路上有許多方法可以搜尋;或是購買市售商品，但是請務必要選擇❮原味無糖優格❯搭配才能吃出其美味喔！添加一些當季新鮮水果、或是綜合莓果，即成健康又美味的【水果優格】！你一定要試試看！', '116.)飲料🍹:冷熱飲皆宜！還可將水果、冷開水、果醬一起攪打成果汁（果醬約1-2大匙即可）']",
#       {'Calorie_correction': 283.0,
#        'Moisture': 33.3,
#        'Crude_protein': 10.0,
#        'Crude_fat': 6.1,
#        'Saturated_fat': 2.9,
#        'Total_carbohydrates': 49.2,
#        'Dietary_fiber': 4.2,
#        'Total_carbohydrate': 6.7,
#        'glucose': 2.1,
#        'fructose': 2.9,
#        'Galactose': 0.0,
#        'maltose': 1.6,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 355.0,
#        'Potassium': 137.0,
#        'calcium': 18.0,
#        'magnesium': 46.0,
#        'iron': 1.3,
#        'Zinc': 1.4,
#        'phosphorus': 130.0,
#        'copper': 0.0,
#        'manganese': 0.0,
#        'VitaminB1': 0.22,
#        'VitaminB2': 0.07,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.21,
#        'VitaminC': 0.0,
#        'Folic_acid': 66.7,
#        'VitaminA': 5.0,
#        'VitaminD': 0.0,
#        'VitaminE': 2.04}],
#      ['1000次梳乎厘奄列',
#       'https://img.cook1cook.com/upload/cover/202005/20/144150-1588396279_thumb.JPG',
#       "['雞蛋']",
#       "['兩隻']",
#       "['1最小火燒熱平底鑊，抹上一層薄油，', '2將蛋白蛋黃分開，蛋白放進大盤，蛋黃放入小碗。用打蛋器打起蛋白，先把蛋白放入雪櫃半小時，蛋白放久了會減低黏稠度，讓空氣更容易打入蛋白中！', '3打至反轉大盤，蛋白不會倒出就可以了，', '4蛋黃打散，加入蛋白中拌勻，記住動作要輕，否則蛋白容易消泡。', '5蛋漿加入平底鑊中，造成圓形，喜歡咸食的可在此時加入芝士及蔥花，蓋上鍋蓋，焗4分鐘，喜歡更熟一點可以多煎1分鐘，', '6奄列的底部形成脆脆外皮後。用鑊鏟輕輕鬆開奄列，將奄列慢慢推向鍋邊，再放到碟上。加上糖漿。']",
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['日式溏心蛋',
#       'https://img.cook1cook.com/upload/cover/202007/20/30114-1594781581_thumb.jpg',
#       "['鸡蛋']",
#       "['']",
#       "['1常溫蛋(若是冰箱取出請放置常溫1小時以上)蛋的\\ue81e兩端分別轻敲至有点裂纹，或可以用大頭針在蛋的兩端分別刺一小孔', '2大火煮開水後，輕輕將蛋放入，转去中火偏小的火力，持續煮6分鐘，（(注明，時間按蛋大小調節一下**不同爐具火力不一，最好先做一次，查看結果，作下次準則））這是比較完美的時間，大概是5-6分熟的狀態，這段時間千萬不要離開鍋，用用具輕輕打圈攪動雞蛋，可令蛋黃固定在蛋的中央，可確保蛋黃在蛋的中心部位，保證切開的時候半截面是完美的形狀', '3時間一到立刻關火放進冰冷水里，待蛋略為降溫，將蛋殼敲裂，再浸在水中，讓水滲進蛋內，會較容易剝殼，小心剝去蛋殼,糖心蛋完成了。', '4將剝好的雞蛋放进醤汁里，（给儿子偷吃两粒了）醬汁一定要淹沒過雞蛋，保證整顆蛋的顏色是均勻的', '5也可做日式风味的醬汁--醬油：味淋：水=1:1:3，混在一起煮開備用泡蛋']",
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['蝦肉炒蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/361106/2969fbf48a208dac.jpg',
#       "['雞蛋']",
#       "['2']",
#       'step-1 \nstep-2 \nstep-3 \n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['菜脯煎蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/363584/0d4fc1b263a2299d.jpg',
#       "['雞蛋']",
#       "['6']",
#       'step-1 \nstep-2 \n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['菜雞飯',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/364298/649f5e6088987207.jpg',
#       "['雞蛋']",
#       "['3']",
#       'step-1 洗淨菜切絲，洗米，放雞\nstep-2 \n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['无油煎鸡蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/364439/1ea4c16497ef9987.jpg',
#       "['鸡蛋']",
#       "['3']",
#       'step-1 打开鸡蛋盖住熟\n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['【簡易炒蛋】兩顆蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/365609/c36b14a26ae86a60.jpg',
#       "['蛋']",
#       "['兩顆']",
#       'step-1 兩顆蛋，均勻打散(不同玫瑰歐姆蛋，不打均勻反而能呈現黃白色澤層次感)\nstep-2 中火熱鍋後蛋液下鍋\nstep-3 因為今日要做的是碎蛋下鍋後就可以開始用矽膠鍋鏟推擠\nstep-4 不斷推擠\nstep-5 差不多8分熟了\nstep-6 起鍋\nstep-7 完成💗\nstep-8 \nstep-9 汪🐶:小激動\nstep-10 搭配 早午餐花生漢堡肉蛋吐司+拿鐵 食譜請至➡️下篇文章觀看謝謝收看😊\n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['[懶人/電鍋]白煮蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/366953/653f6acfcc2f9d9c.jpg',
#       "['蛋']",
#       "['7個']",
#       'step-1 蛋放上蛋架。電鍋一杯水。\n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['原味舒芙蕾烘蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/368558/39e28d06a773fd8a.jpg',
#       "['雞蛋']",
#       "['兩顆']",
#       'step-1 先將蛋白蛋黃分離\nstep-2 蛋白部分打致硬性發泡\nstep-3 將兩者混合均勻\nstep-4 \nstep-5 鍋內均勻抹上奶油（全程小火）\nstep-6 倒入雞蛋糊（蓋上鍋蓋悶3-4分鐘）\nstep-7 折半盛起即可\nstep-8 \n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['零技術歐姆蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/369488/27f476b71229431c.jpg',
#       "['雞蛋']",
#       "['2顆']",
#       'step-1 將蛋白和蛋黃分開\nstep-2 把蛋白打發成泡沫狀*建議用電動攪拌機打發*\nstep-3 將蛋黃和打發的蛋白混合均勻\nstep-4 熱鍋以後加入油將混合後的蛋液倒入鍋中注意火候\nstep-5 中間也可以包起司等喜歡的料\nstep-6 之後將底部成形的蛋對折就可以出鍋\n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['溏心蛋半熟蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/369505/c5a5e03edda50bb7.jpg',
#       "['蛋']",
#       "['1']",
#       'step-1蛋放至室溫。\nstep-2水滾下蛋，煮三分鐘，熄火焗三分鐘。\nstep-3用水喉水降溫後，在水中剝殼。\n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['神奇鸡蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/344298/cd2774bfa32afa82.jpg',
#       "['鸡蛋']",
#       "['3']",
#       'step-1 \n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['創意鮭魚芙蓉蒸蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/346654/e8adcfaf0abde1cf.jpg',
#       "['雞蛋']",
#       "['10顆']",
#       'step-1雞蛋與水二比四\n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['迷你煎蛋',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/349814/8099f05de213fb20.jpg',
#       "['雞蛋']",
#       "['3顆']",
#       'step-1 先清洗雞蛋的外殼，然後放進封口袋。\nstep-2 置冰箱冷凍庫，直至雞蛋完全結凍。\nstep-3 凍雞蛋由冷凍庫取出後，沖水幾秒、即可輕鬆剝下蛋殼。\nstep-4 迅速將凍蛋切片、置盤中。\nstep-5 熱鍋、倒入些許蔬菜油，把凍蛋切片逐一排入鍋裡。\nstep-6 蛋單面煎至金黃色，翻面煎另一面；\nstep-7 煎至蛋雙面熟、微焦，即可熄火。\nstep-8 三顆雞蛋，即可煎出一大盤迷你煎蛋，增添生活樂趣。\nstep-9 正餐、點心或是便當菜，都適宜。\n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}],
#      ['飛利浦氣炸鍋》氣炸雞蛋社頭店',
#       'https://tokyo-kitchen.icook.network/uploads/recipe/cover/354309/c6bcf6fe81c1e753.jpg',
#       "['雞蛋']",
#       "['2顆']",
#       'step-1 氣炸溫度180度，時間10分鐘\nstep-2 完成了\n',
#       {'Calorie_correction': 135.0,
#        'Moisture': 75.9,
#        'Crude_protein': 12.7,
#        'Crude_fat': 8.9,
#        'Saturated_fat': 3.1,
#        'Total_carbohydrates': 1.6,
#        'Dietary_fiber': 0.0,
#        'Total_carbohydrate': 0.2,
#        'glucose': 0.2,
#        'fructose': 0.0,
#        'Galactose': 0.0,
#        'maltose': 0.0,
#        'sucrose': 0.0,
#        'lactose': 0.0,
#        'sodium': 138.0,
#        'Potassium': 135.0,
#        'calcium': 54.0,
#        'magnesium': 11.0,
#        'iron': 1.9,
#        'Zinc': 1.3,
#        'phosphorus': 186.0,
#        'copper': 0.07,
#        'manganese': 0.03,
#        'VitaminB1': 0.09,
#        'VitaminB2': 0.48,
#        'VitaminB6': 0.11,
#        'VitaminB12': 0.8,
#        'VitaminC': 0.6,
#        'Folic_acid': 78.6,
#        'VitaminA': 558.0,
#        'VitaminD': 84.4,
#        'VitaminE': 2.22}]]
#     return left
#
#
# # def input_column(recipes):
# #     if recipes == '{查無符合資料}':
# #         text_message = TextSendMessage(text='查無符合資料')
# #         line_bot_api.reply_message(event.reply_token, text_message)
# #
# #
# #     else:
# #         columnlist = []
# #         for recipe in recipes:
# #             column = CarouselColumn(
# #                 thumbnail_image_url=f'{recipe[0]}',
# #                 title=f'{recipe[1]}',
# #                 text=f'{recipe[2]}',
# #                 actions=[
# #                     URITemplateAction(
# #                         label=f'{recipe[1]}作法影片',
# #                         uri=f'{recipe[3]}'
# #                     ),
# #                     URITemplateAction(
# #                         label=f'{recipe[1]}食譜查詢',
# #                         uri=f'{recipe[4]}'
# #                     ),
# #                     MessageTemplateAction(
# #                         label=f'{recipe[1]}營養素',
# #                         text=f'{recipe[5]}')
# #                 ]
# #             )
# #             columnlist.append(column)
# #         print(columnlist)
#         # Carousel_template = TemplateSendMessage(
#         #     alt_text='Carousel template',
#         #     template=CarouselTemplate(
#         #         columns=columnlist))
#         # line_bot_api.reply_message(event.reply_token, Carousel_template)
#
# # recipelist = left()
# # a = tool.recipetempelete(recipelist)
# # b= tool.input_column(a)
# # print(b)
# # recipes = tool.recipetempelete(recipelist)
# # input_column(recipes)
#
# # def recipeurl(left):
# #     myfinaldict = {}
# #     namelist = []
# #     urllist = []
# #
# #     for content in left[0:6]:
# #         name = content[0]
# #         imgurl = content[1]
# #         # print(name)
# #         # print(imgurl)
# #         if imgurl[0:11] == r'https://img':
# #             namelist.append(name)
# #             url =f"https://cook1cook.com/search?keyword={name}&theme=recipe"
# #             urllist.append(url)
# #         elif imgurl[0:11] == r'https://tok':
# #             namelist.append(name)
# #             url = f'https://icook.tw/search/{name}'
# #             urllist.append(url)
# #     mydict = dict(zip(namelist, urllist))
# #     myfinaldict.update(mydict)
# #     return myfinaldict
# # print(recipeurl(left))
# # #尋找yt
# # def ytname(name):
# #     return f'https://www.youtube.com/results?search_query={name}'
# #
# # def nutrient(left):
# #
# #     if len(left) > 6:
# #          myfinaldict = {}
# #          namelist = []
# #          nutrientlist = []
# #          for content in left[0:6]:
# #              # for i in content[5]:
# #              #     print
# #              # print(content)
# #              name = content[0]
# #              # print(name)
# #              nutrientsentence = ''
# #              for nutrient , weight in content[5].items():
# #                  nutrientsentence += (f'營養素名:{nutrient},重量:{weight}\n')
# #              namelist.append(name)
# #              nutrientlist.append(nutrientsentence)
# #          mydict = dict(zip(namelist, nutrientlist))
# #          myfinaldict.update(mydict)
# #          return myfinaldict
# #
# # # print(nutrient(left))
# # # def manageForm(event,msg):
# # #     try:
# # #         flist = msg[3:].split('/')
# # #         text1 = '姓名' +flist[0] + '/n'
# # #         text1 += 'email' + flist[1] + '/n'
# # #         text1 += '性別' + flist[2] + '/n'
# # #         text1 += '年齡' + flist[3] + '/n'
# # #         text1 += '身高' + flist[4] + '/n'
# # #         text1 += '體重' + flist[5] + '/n'
# # #         text1 += '不能吃' + flist[6] + '/n'
# # #         text1 += '養生' + flist[7] + '/n'
# # #         text1 += '油炸' + flist[8] + '/n'
# # #         text1 += '蔬果攝取' + flist[9] + '/n'
# # #         text1 += '活動量' + flist[10]
# # #         message = TextSendMessage(text = text1)
# # #         line_bot_api.reply_message(event.reply_token,message)
# # #     except:
# # #         line_bot_api.reply_message(event.reply_token,
# # #                                    TextSendMessage(text='發生錯誤!'))
# # a={}
# # b={1:2}
# # a.update(b)
# # print(a)
#
# # print(urllib.parse.quote('雲朵蛋'))
#
# # string = "python"
# # print(string[-4:])
#
# # sentence = '###085/778/男/17歲以下/616/999/124/是/是/是/輕度活動'
# # source = sentence.split('/')
# # username = source[0].split('###')[1]
# # # user_id = user_id
# # email = source[1]
# # gender = source[2]
# # age = source[3]
# # height = source[4]
# # weight = source[5]
# # disliked = source[6]
# # health = source[7]
# # fried = source[8]
# # vegetable = source[9]
# # activity = source[10]
# #
# # cur = mysql.connection.cursor()
# # increase = f"""INSERT INTO USER VALUES(
# #          '{username}','{user_id}','{email}','{gender}','{age}','{height}','{weight}','{disliked}','{health}','{fried}','{vegetable}','{activity}')"""
# # cur.execute(increase)
# # mysql.connection.commit()
# # a= (1,2,3)
# # b=()
# # print(a[1])
# # print(len(a))
# # print(len(b))
#
# a=[1,2,3]
# # print(list(a))
# print(a[-1])